# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         MMS-MailParser
version:      0.02
version_from: lib/MMS/MailParser.pm
installdirs:  site
requires:
    MIME::Parser:                  0
    MMS::MailMessage:              0.02
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
